/**
 * Application types for the offshoreproz-agent-api Worker.
 *
 * The global `Env` interface is generated by `wrangler types` into
 * worker-configuration.d.ts. This file:
 *  1. Re-exports Env as a named export for use in Hono generics
 *  2. Augments global Env with optional Sprint 4+ secrets
 *  3. Defines all application-level types (formations, webhooks, etc.)
 *
 * After any binding change in wrangler.jsonc, regenerate:
 *   cd workers/agent-api && npx wrangler types
 */

// ─── Env ──────────────────────────────────────────────────────────────────────
// Re-export the global Env for Hono generics: `Hono<{ Bindings: Env }>`
// The global declaration lives in worker-configuration.d.ts (generated by wrangler types).
// We declare it here as well so it can be imported as a named export.
export interface Env {
  // D1 Databases
  AGENT_DB: D1Database;
  PORTAL_DB: D1Database;
  // KV Namespace
  KV: KVNamespace;
  // R2 Bucket
  R2: R2Bucket;
  // Variables
  ENVIRONMENT: "development" | "staging" | "production";
  API_VERSION: string;
  API_BASE_URL: string;
  PORTAL_URL: string;
  PORTAL_DOCS_DB_ACCOUNT_ID: string;
  /**
   * ⚠️ SAFETY FLAG — controls whether Agent API writes to PORTAL_DB.
   *
   * "false" (default) = dry-run mode: portal-db.ts logs what would be written
   *   but makes no DB mutations. Safe for staging and local dev.
   *
   * "true" = live writes: INSERT into projects/documents/invoices in portal DB.
   *   Only set "true" in the production environment after migration 082 is applied.
   *
   * String type because Cloudflare vars are always strings.
   */
  PORTAL_SYNC_ENABLED: string;
  /**
   * ⚠️ LIVE GATE — controls whether op_live_ keys are honored.
   *
   * "false" (default) = closed gate: live keys are rejected, only op_test_
   *   (sandbox) works. No real charges or filings.
   *
   * "true" = open gate: op_live_ keys are accepted (real charges + real filing).
   *   Flip to "true" in the PRODUCTION env ONLY, as the final live-gate step.
   *
   * Read via isLiveModeEnabled() in config/live-mode.ts by BOTH middleware/auth.ts
   * and routes/mcp.ts, so REST and MCP can never be half-open. String type because
   * Cloudflare vars are always strings.
   */
  LIVE_MODE_ENABLED: string;
  // Secrets
  API_KEY_ENCRYPTION_SECRET: string;
  // Provider secrets (set via `wrangler secret put <NAME>`)
  STRIPE_SECRET_KEY?: string;        // ← env.local STRIPE_SECRET_KEY_LIVE
  STRIPE_WEBHOOK_SECRET?: string;    // ← env.local STRIPE_WEBHOOK_SECRET_AGENT_API
  KYC_PROVIDER_KEY?: string;         // ← env.local STRIPE_IDENTIFYING_KEY_AGENT_API
  SIGNING_PROVIDER_KEY?: string;     // ← env.local DOCUSEAL_API_KEY
  DOCUSEAL_TEMPLATE_ID_WY?: string;  // numeric template ID for WY operating agreement
  DOCUSEAL_TEMPLATE_ID_MI?: string;  // numeric template ID for MI DAO LLC operating agreement
  DOCUSEAL_WEBHOOK_SECRET?: string;  // set in DocuSeal dashboard → webhook secret
  /** Sprint 7: bearer token gating admin/ops endpoints (manual-assisted filing). */
  ADMIN_API_TOKEN?: string;
  /** B5: Resend API key for transactional emails (OTP verification for live key creation). */
  RESEND_API_KEY?: string;
}

// ─── Hono app type ────────────────────────────────────────────────────────────
// Use `AppType` as the generic parameter for all Hono instances so that
// `c.get('trace_id')` is correctly typed throughout the codebase.
// Usage: `new Hono<AppType>()` or `Hono<AppType>` in function signatures.

export interface AppVariables {
  trace_id: string;
  api_key_id?: string;
  api_key_mode?: "test" | "live";
  api_key_tier?: "free" | "pro" | "enterprise";
}

export type AppType = {
  Bindings: Env;
  Variables: AppVariables;
};

// ─── Formation ───────────────────────────────────────────────────────────────

export type FormationStatus =
  | "draft"
  | "pending_owner_confirmation"
  | "portal_synced"
  | "kyc_pending"
  | "kyc_review"
  | "kyc_failed"
  | "payment_pending"
  | "payment_authorized"
  | "signature_pending"
  | "filing_ready"
  | "filing_in_progress"
  | "registration_complete"
  | "documents_ready"
  | "ein_pending"
  | "complete"
  | "action_required"
  | "failed"
  | "kyc_approved"
  | "cancelled";

export type FormationMode = "test" | "live";

export type JurisdictionCode = "WY" | "MI" | "NV" | "BVI" | "PA" | "UAE";

// ─── API Keys ─────────────────────────────────────────────────────────────────

export type ApiKeyTier = "free" | "pro" | "enterprise";
export type ApiKeyMode = "test" | "live";

/** Row shape returned from AGENT_DB.agent_api_keys */
export interface DbApiKey {
  id: string;
  key_hash: string;
  mode: ApiKeyMode;
  name: string;
  owner_email: string;
  tier: ApiKeyTier;
  created_at: string;
  last_used_at: string | null;
  revoked_at: string | null;
}

/** Row shape returned from AGENT_DB.agent_formations */
export interface DbFormation {
  id: string;
  mode: FormationMode;
  api_key_id: string;
  status: FormationStatus;
  jurisdiction: JurisdictionCode;
  company_name: string;
  portal_project_id: string | null;
  portal_client_id: string | null;
  estimate_id: string | null;
  amount_total_usd: number | null;
  stripe_payment_intent_id: string | null;
  signing_provider: string | null;
  signing_envelope_id: string | null;
  request_json_encrypted: string | null;
  agent_context_json: string | null;
  owner_type: "human" | "ai_agent";
  error_code: string | null;
  error_message: string | null;
  created_at: string;
  updated_at: string;
  completed_at: string | null;
}

// ─── Request context ──────────────────────────────────────────────────────────

/** Variables stored in Hono context (c.var) for the duration of a request */
export interface RequestContext {
  trace_id: string;
  api_key_id?: string;
  api_key_mode?: ApiKeyMode;
  formation_id?: string;
  portal_project_id?: string;
}

// ─── Structured logging ───────────────────────────────────────────────────────

export interface LogEvent {
  ts: string;
  level: "info" | "warn" | "error";
  message: string;
  trace_id: string;
  // Optional correlations (never include raw PII like passport/address)
  api_key_id?: string;
  formation_id?: string;
  portal_project_id?: string;
  status_code?: number;
  duration_ms?: number;
  method?: string;
  path?: string;
  error?: string;
  [key: string]: unknown;
}

// ─── API response shapes ──────────────────────────────────────────────────────

export interface ApiErrorResponse {
  error: string;
  code: string;
  request_id: string;
  docs?: string;
  issues?: unknown[];
}

export interface ApiSuccessResponse<T> {
  data: T;
  request_id: string;
}

// ─── Next action (returned in formation status) ───────────────────────────────

export interface NextAction {
  type:
    | "owner_confirmation"
    | "human_kyc"
    | "payment"
    | "signature"
    | "waiting_filing"
    | "retry";
  label: string;
  url: string;
  expires_at: string | null;
}
